

#NUMERO DE PAGINAS A COLETAR DO PRIMEIRO LINK (NÃO INCLUIR A ULTIMA PAGINA)
numPaginas1 = 0


#NUMERO DE PAGINAS A COLETAR DO SEGUNDO LINK 
numPaginas2 = 0


#BOOL (True ou False) - ACIONAR SE QUISER INCLUIR QUESTOES DISSERTATIVAS
aceitarDiscursivas = False


#BOOL (True ou False) - ACIONAR SE EXERCICIOS TIVEREM BOTAO "VER TEXTO" P/ REVELAR TEXTO 
portugues = True


#BOOL (True ou False) - ACIONAR SE APENAS QUISER QUESTOES DISCURSIVAS
apenasDiscursivas = False 



#STRINGS - TODOS OS VALORES ABAIXO DEVEM ESTAR ENTRE ASPAS:

#LINK DO SOEXERCICIOS.COM.BR COM TODOS OS FILTROS DE VESTIBULAR E ASSUNTO (SELECIONAR NO SITE)
#VÁ PARA A SEGUNDA PÁGINA DE RESULTADOS DO SITE ANTES DE COLETAR O LINK
primeiro_link = "soexercicios.com.br/exemplo&page=xyz"

#SEGUNDO LINK(OPCIONAL)
segundo_link = "soexercicios.com.br/exemplo&page=xyz"

#NOME DA LISTA - DEVE TERMINAR COM .PDF
nomeLista = "exemplo.pdf"